### ISSUE TITLE
Custom javascript and css Modal stopped working when clicked on Test

### ISSUE THREAD

**Issue by arshwarsi** [anshooarora/extentreports-java#1061]
HI Anshoo,

I have added javascript and css in custom javascript section in config file xml for Modal Dialog.

`public static void main(String[] args) {
		ExtentReports extentreport = ExtentReportUtil.getXMLConfigExtent("src/test/resources/ReportsPCIN/Sample.html","src/test/resources/ReportsPCIN/extent-configDSI.xml","SampleModalProblem");
    	ExtentTest parentTest = extentreport.createTest( "TC1 Sample");
		parentTest.log(Status.INFO,"TestStep 1");
		parentTest.log(Status.INFO, new ExtentModal("REQUEST PAYLOAD","Request","ABC request Message"));
		parentTest.log(Status.INFO, new ExtentModal("RESPONSE PAYLOAD","Response","XYZ response Message"));
		ExtentTest parentTest2 = extentreport.createTest( "TC2 Sample");
		parentTest2.log(Status.INFO,"TestStep 1");
		ExtentReportUtil.getExtent().flush();
	}`

Modal is working fine when page is loaded and button is clicked , but when i click on TestCase name or other testcase and again try to come back and click on button , the custom Javascript doesn't get fired then.

Its not an issue for you. Thanks . I am closing.

**Comment by arshwarsi** [comment]
Its not an issue for you. Thanks . I am closing.

**Comment by anshooarora** [comment]
Due to existing engagements and managing 5 repositories,  it is very difficult to reply to each ricket unless it is an issue.  What you are doing is supported by default in the professional version and I am not sure how to recreate this functionality correctly in this way without some research. Also, all customizations are left up to the user and I generally do not respond to those as they open door to many similar queries which I will never be able to attend to given my current schedule.
