### ISSUE TITLE
Showing Test case Status as Pass for Skipped test case

### ISSUE THREAD

**Issue by rganjare** [anshooarora/extentreports-java#592]
Hi Anshoo,
I am using Extent Report 1.4 with Java 1.7. 
Report showing test case status as "Pass", when test case is Skipped as Run Mode is set to "No". The Test case status should be Skipped.
![report screen shot](https://cloud.githubusercontent.com/assets/20878371/17738004/151bc362-64ad-11e6-81ef-6c5fa2de401f.PNG)

And My program for Skipping test case is 
 else {
					report.log(LogStatus.SKIP, "Skipped " + testCase + " test case as Run Mode was N");
					throw new SkipException("Skipped " + testCase + " test case as Run Mode was N");
				}

**Comment by anshooarora** [comment]
This is not possible for the version you are using as the priority for PASS is higher than SKIP.  I would recommend upgrading to version 3.0,  but since its in pre-release,  at least to 2.41.1 which defines the priority higher for SKIP so this issue will go away.  

Version 2 & 3 has breaking changes so you will have to change your code.  You will find complete docs for version 2 [here](http://extentreports.relevantcodes.com/).  Version 3 docs [here](https://github.com/anshooarora/extentreports-java/blob/master/README.md).

**Comment by rganjare** [comment]
Thank You Anshoo for your quick response. Let me implement extents version V 2.41.1. In case any question will disturb you again.

Thank You
Rahul Ganjare

**Comment by rganjare** [comment]
Hi Anshoo,
I have implmented the Extent Report V2.41.1 in my project, It's really appriciable. 
I want to customize this report also. I don't want Steps View chart in my report. And want a PI chart report.
Is it possible to customize V2.41.1. I tried with Configuration file "extent.loadConfig(new File(Constants.REPORT_XML));" but it's just titles we can change.
