### ISSUE TITLE
[Question] V3 - not to log skip or failed tests on retry

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports-java#651]
In v3 i have two questions mainly..
Which flag has to be used for overwriting test that has failed due to one reason on the first try and on the next retry, the test passes. In the report it must have the latest result updated for that particular test keeping other results unchanged.
I'm migrating from v2.41 extentreports java to v3. Could not find the documentation regarding having NetworkMode OFFLINE and ONLINE versions of the reports.Could you please let me know some insights on it.

P.S:picked this from gitter as @saikiran40cs asked this question, which even i wanted to know

**Comment by anshooarora** [comment]
As I replied to @saikiran40cs at gitter: both these features are currently not available in 3.0. Online/Offline will not be available, and I am still debating (and may add it) on providing the feature to overwrite existing HTML files in this version. The pro version to be released in a few weeks will have both these features though.

The template in version 3.0 is extremely complicated and so is the ability to overwrite an existing file which is why it is not currently included in the open-source version but if there is a big need, will surely add it.
