### ISSUE TITLE
Null pointer exception unless the report is attached

### ISSUE THREAD

**Issue by email2vimalraj** [anshooarora/extentreports-java#666]
Extent version: v3.0.0

I'm creating an instance for the `ExtentReports` at the beginning of the execution and I don't want to attach any reporter unless the execution is completed. So I'm attaching the reporter at the end of the execution. So I'm performing like this:

**On Execution Start**
```java
ExtentReports extent = new ExtentReports();
```

**On Test start**
```java
ExtentTest test = extent.createTest("Test Name");  // Getting null pointer exception here
```

**On Execution Complete**
```java
ExtentHtmlReporter reporter = new ExtentHtmlReporter(filePath);
extent.attachReporter(reporter);
extent.flush();
extent.close();
```

The `Null pointer exception` is thrown while creating the test. To reproduce, execute the following:

```java
    public static void main(String[] args) {
        ExtentReports extent = new ExtentReports();
        ExtentTest test = extent.createTest("Test Name");
        test.pass("Passed");

        ExtentHtmlReporter reporter = new ExtentHtmlReporter("output/test.html");
        extent.attachReporter(reporter);
        extent.flush();
        extent.close();
    }
```

**Comment by anshooarora** [comment]
In version 3, ExtentReports is just a facade - it requires reports to be able to do the actual reporter.  The reporters get collections and are also listeners so when a test is started, log is added, category is assigned etc. the reporters are notified.  See [here](https://github.com/anshooarora/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/TestListener.java) for the complete list.

If you are starting a test without a started reporter, the listening aspect of the reporter will fail because there are no attached reporters.  Obviously, a NullPointerException must be handled and replaced with a meaningful message ( will fix in the upcoming ) but this behavior will cause other side-affects.

**Comment by anand462** [comment]
How do u attach a reporter

**Comment by anand462** [comment]
do u have a scala plugin
