### ISSUE TITLE
Would like to have screenshot for each steps in V 3.0.2

### ISSUE THREAD

**Issue by Vishnu1067** [anshooarora/extentreports-java#766]
Hi @anshooarora ,

As i reported in wrong channel before, https://github.com/anshooarora/extentx/issues/89 
I would like to have screenshots for every step after perform the actions. 

In V 2.41.2, i have an option to add screenshot for each step as `ExtentTestManager.getTest().addScreenCapture(capturedScreen)`. This function helps to add screenshot for each step. 

In V 3.0.2 we have `ExtentTestManager.getTest().addScreenCaptureFromPath(capturedScreen);` which adding in test steps but not for each steps.

**Comment by anshooarora** [comment]
See here:  http://extentreports.com/docs/versions/3/java/#insert-screenshots

```
// adding screenshots to log
test.fail("details", MediaBuilder.createScreenCaptureFromPath("screenshot.png").build());

// or:
MediaModelProvider mediaModel = MediaBuilder.createScreenCaptureFromPath("screenshot.png").build();
test.fail("details", mediaModel);	
```

```
// adding screenshots to test
test.fail("details").addScreenCaptureFromPath("screenshot.png");
```

**Comment by savvyaxnjxn** [comment]
@Vishnu1067 - I have created a fairly simple method that I call frequently (albeit not EVERY step) that adds many screenshots to my tests.  It is based upon @anshooarora's suggested examples and you can view a copy of it on the 03FEB2017 comment of issue #726.  I have used it with great success in v3.0.2.  Modify it to your heart's content to fit your style; I hope it helps~

**Comment by Vishnu1067** [comment]
@savvyaxnjxn Thanks a lot. This is what exactly i want. Cheers!

**Comment by SapizonTechnologiesLLP** [comment]
Hi @anshooarora ,
I have created a method to capture the screenshots am calling this method when ever i want to capture the screenshot am attaching this screenshots to the INFO i.e test.log(LogStatus.INFO, "Enter Valid Password"+test.addScreenCapture()); am successfully executing the test on local machine am able to view the screenshots with respect to INFO logs in local machine. Am trying to run the same test on jenkins i have done all the configuration perfectly in jenkins but the issue is am not able to the screenshots when i run the test on jenkins .
![snip20171130_1](https://user-images.githubusercontent.com/31738192/33428203-f1881ad2-d5ed-11e7-91e4-e70ca5208fd5.png) please guid me regarding this issue.

Thank you.
