### ISSUE TITLE
How to allow only last run test's status and count when run via Retry feature in TestNG

### ISSUE THREAD

**Issue by rahulr892** [anshooarora/extentreports-java#806]
I have a project with retry feature = 1 in TestNG

The report shows all the test runs including fail and pass

If a test fails and after rerun it fails again then count = 2 but it should be count = 1 and a fail
If a test fails and after rerun it passes then count = 2 but it should be count = 1 and a pass

How do I do this in extent reports ?

**Comment by savvyaxnjxn** [comment]
@rahulr892 - This is a tricky one.  It sounds like I have a very similar setup with TestNG retries and had a very similar thought for an Extent enhancement.  I do not know of a way to circumvent the counts you are getting because I am seeing the very same thing.  However, on occasion it has actually been helpful to me to further hone/fix my tests when I noticed that the same ones were getting retried over and over again.   Perhaps some sort of xml config option to set how this behavior acts?

TestNG doesn't even handle this perfectly: in your described example (or, at least in my setup), TestNG would report the following:
If a test fails and after rerun it fails again then count = 2 but (TestNG) reports 1 fail and 1 skip
If a test fails and after rerun it passes then count = 2 but (TestNG) reports 1 pass and 1 skip

Perhaps a similar 'skip' designation that doesn't get counted toward the final/net count in Extent?  I know Extent has an option to mark a step in such a way, but I haven't seen any examples of it being used.

**Comment by anshooarora** [comment]
This is by design.  Extent in this case will not report the same as what TestNG will as the retry logic is not present.  It will report all tests which were executed, and that is also the correct representation of the entire execution cycle.

An enhancement can be created to allow deleting tests that have been retried explicitly by the user as I do not plan to make this feature turned on "by default".  Please feel free to open a new ticket for the enhancement.

**Comment by preetkk** [comment]
can u please provide the guide how to override failed test case as u append the extent report

**Comment by preetkk** [comment]
I have same issue while am using setAppendExisting(true) to have all results in the same report.
Unfortunately it gives me (after one run and then re-run of failed testes) something like that:
(in the left 'Tests' column)
TEST1 PASS
TEST2 PASS
TEST3 FAIL
TEST4 FAIL
TEST3 PASS
TEST4 FAIL
