### ISSUE TITLE
Merge reports is removing Categories assigned for the tests in first report

### ISSUE THREAD

**Issue by vamsimadaka** [anshooarora/extentreports-java#837]
![merged report - categories view](https://cloud.githubusercontent.com/assets/25842448/24576342/1e8ec9a2-16d8-11e7-8932-5ebe4bc58d7f.png)
![after merge - report - categories of first run tests removed out](https://cloud.githubusercontent.com/assets/25842448/24576344/1e8f361c-16d8-11e7-8a67-7d6d0a2d104b.png)
![first run report - categories view](https://cloud.githubusercontent.com/assets/25842448/24576343/1e8edd02-16d8-11e7-87cd-8cda2b30f1a5.png)

## Summary

I'm using TestNGITestListener for extent reports. Using parent and child nodes. Extent reports Version 3.0.1.
Setting the categories to the child tests.
When I'm merging 2 reports - then the categories set for the tests executed in first report are getting removed after merge. I can see only categories of the tests executed during 2nd run.

## Expected Behavior
Categories of the first run tests should retain.

## Current Behavior
Categories of the 2nd run tests only showing up in the merged report.

## Environment Details

* Extent report Version used: 3.0.1
* Operating System and version: Window7 64 bit
* JDK Version: 1.8.0_121

**Comment by rdivahar** [comment]
Hi @anshooarora , 

I am using the latest version (3.0.7) of extent-reports, and I am encountering exactly the same issue as @vamsimadaka . 

### Summary:
I am merging two reports using `htmlReporter.setAppendExisting(false);` and it works with no issues except the merging of tests based on category. **The category section only has the tests that is associated with the second report and missing the tests from the first report.** Whereas, the other sections displays the results of all the tests. 

### Expected Behavior: 
The category section should display the all tests. Both from the first report + second report with the corresponding category tag. 

### Current; 
The category section only shows up the tests from the latest appended report (2nd  @report). Attached screenshots below. 

### Dashboard View:
![image](https://user-images.githubusercontent.com/27971800/31794977-14e0c5aa-b4f2-11e7-9f50-9968c20db951.png)

### Category View:

> Category view doesn't display up all the tests (merged), instead it shows up only the tests that is associated with the last appended tests from the second report. 

![image](https://user-images.githubusercontent.com/27971800/31795157-bd8db79e-b4f2-11e7-927c-1ecd37870d9b.png)

**Comment by SwathiReddygovind** [comment]
@rdivahar 
Hi Divahar
Did you get the soultion @rdivahar .Even I am facing the same issue in 3.0.3.

If it is fixed please tell me solution.
