### ISSUE TITLE
Unify files 

### ISSUE THREAD

**Issue by beeva-victorinojimenez** [anshooarora/extentreports-java#861]
## Summary

I have a performance problem creating a single html report file. 
I have 3250 test and if I create an only file report the time of run test is the one hour. If I create an file report by testSuite, the time of run test is the ten minutes.

## Expected Behavior

With this problem with the performance, I would like unify all files reports generated in a new file report with all previous reports

Is there a function for than I can unify all files in a new single file?

**Comment by anshooarora** [comment]
With a huge test count, you can use the ExtentXReporter (ExtentX will provider better performance here)  only.  I wouldn't recommend using the static HTML reporter as due to the file size, performance would obviously suffer.  Even if you merge your reports into 1, as long as its a static file, you will still have same performance issues.  Also, there is no way to merge these reports into 1..
