### ISSUE TITLE
Dashboard view is not active while opening the report

### ISSUE THREAD

**Issue by sureshdubey** [anshooarora/extentreports-java#892]
Hi,

I'm using extent report latest version in our TestNG project. Everything is working perfectly except one thing. On opening, the report test view is active by default, which has a lot of detail information. Are there any ways by which we can activate dashboard view right after opening the report?

**Comment by email2vimalraj** [comment]
@sureshdubey : There is no direct way to make the dashboard as the default view. There are two workarounds:
1. Either make the charts visible on the test view as mentioned here: [http://extentreports.com/docs/versions/3/java/#htmlreporter-configuration](http://extentreports.com/docs/versions/3/java/#htmlreporter-configuration)
2. Otherwise, inject some javascript on document load to make the dashboard view visible by default using something like this:
```javascript
document.querySelector('a[view=test-view]').parentElement.classList.remove('active');
document.querySelector('a[view=dashboard-view]').parentElement.classList.add('active');
document.querySelector('a[view=dashboard-view]').click();
```

**Comment by ashkaps** [comment]
Hi @email2vimalraj/ @sureshdubey, I have the same issue. I want to have the dashboard view open as default. The second work around that you suggested, do i make this change in extent-config.xml? I am pretty new to extent reports. Can you provide some direction here?
