### ISSUE TITLE
Is there a way to update the total time on the dashboard when i use  htmlReporter.setAppendExisting(true);

### ISSUE THREAD

**Issue by pujaranichand** [anshooarora/extentreports-java#981]
Hi Anshoo,

   if I set the  htmlReporter.setAppendExisting(true); then the dashboard timing and the testcases timings do not match. Is there a way by which I can get the dashboard timing updated with the total time taken by the testcases? So that the dashboard and the testcases are in sync.

Thanks
Puja

**Comment by anshooarora** [comment]
When you use appendExisting with a considerable tine gap between the 2 runs, the start time of the first run and end time of the second determine the total time taken. I generally do not recommend using this feature due to this very side affect.  

Can you customize the reporter to build your tests without this flag?

**Comment by vvigneshbabu** [comment]
I am using the same in C# (3.0.2), it is not working . Could you please provide the fix or any work around
